### ISSUE TITLE
BOT_TIMEZONE - Ошибка

### ISSUE THREAD

**Issue by burjuyz** [melax08/birthdaygram#1]
Ругается на BOT_TIMEZONE, прописывал в env и убирал все равно не помогает... 
`birthdaygram_birthdaygram_bot_1 exited with code 1
birthdaygram_bot_1  | Traceback (most recent call last):
birthdaygram_bot_1  |   File "/app/bot.py", line 4, in <module>
birthdaygram_bot_1  |     from bot.constants.constants import BIRTHDAYGRAM_LOG_NAME, BOT_TIMEZONE, TOKEN
birthdaygram_bot_1  |   File "/app/bot/constants/constants.py", line 27, in <module>
birthdaygram_bot_1  |     ECHO: int = int(os.getenv("ECHO", default=0))
birthdaygram_bot_1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
birthdaygram_bot_1  | ValueError: invalid literal for int() with base 10: ''
`

**Comment by melax08** [comment]
Привет, похоже что жалуется на значение переменной окружения ECHO, там значение нужно устанавливать либо 1 либо 0. Если все верно установлено, покажи .env файл.

**Comment by burjuyz** [comment]
енв стандартный из example, введен только токен бота и все. 
Про переменные куда их нужно внести?

**Comment by melax08** [comment]
в .env для ECHO надо указать либо 1 либо 0, либо полностью удалить данную переменную, тогда будет подтягивать значение по умолчанию: 0.
Для BOT_TIMEZONE можно либо указать свою таймзону, либо тоже удалить данную переменную, тогда будет по умолчанию: Europe/Moscow

**Comment by burjuyz** [comment]
ECHO 1 - только сработал. 
Последний вопрос, в группу или в канал его можно добавлять?

**Comment by melax08** [comment]
Не изучал данный вопрос. Бот изначально был рассчитан для работы в отдельном чате, не уверен что он может работать в группах или каналах. Я еще не писал ботов для таких целей, поэтому, не знаю как они взаимодействуют с телеграмом. Если появится какая-либо информация, сообщите, пожалуйста.

**Comment by melax08** [comment]
UPD. Бот без проблем работает в группах, чтобы передавать ему команды, нужно выделить сообщение бота и нажать "reply", после чего, писать ему. Пример диалога с ботом в группе: 
![image](https://github.com/user-attachments/assets/1809bc79-45a8-44ba-8c7f-ff6d40572f38)
